/* gmdcc.h
 * Header file for C-style interface to the GMD library
 * generated by apiwrapper for GAMS Version 24.8.3
 * Copyright (c) 2016, GAMS Development Corp.
 */

#if ! defined(_GMDCC_H_)
#     define  _GMDCC_H_

#define GMDAPIVERSION 2



enum gmdActionType {
  GMD_PARAM  = 0,
  GMD_UPPER  = 1,
  GMD_LOWER  = 2,
  GMD_FIXED  = 3,
  GMD_PRIMAL = 4,
  GMD_DUAL   = 5  };

enum gmdUpdateType {
  GMD_DEFAULT    = 0,
  GMD_BASECASE   = 1,
  GMD_ACCUMULATE = 2  };

enum gmdInfoX {
  GMD_NRSYMBOLS = 0,
  GMD_NRUELS    = 1  };

enum gmdSymInfo {
  GMD_NAME      = 0,
  GMD_DIM       = 1,
  GMD_TYPE      = 2,
  GMD_NRRECORDS = 3,
  GMD_USERINFO  = 4,
  GMD_EXPLTEXT  = 5  };

#include "gclgms.h"

#if defined(_WIN32)
# define GMD_CALLCONV __stdcall
#else
# define GMD_CALLCONV
#endif

#if defined(__cplusplus)
extern "C" {
#endif

struct gmdRec;
typedef struct gmdRec *gmdHandle_t;

typedef int (*gmdErrorCallback_t) (int ErrCount, const char *msg);

/* headers for "wrapper" routines implemented in C */
int gmdGetReady  (char *msgBuf, int msgBufLen);
int gmdGetReadyD (const char *dirName, char *msgBuf, int msgBufLen);
int gmdGetReadyL (const char *libName, char *msgBuf, int msgBufLen);
int gmdCreate    (gmdHandle_t *pgmd, char *msgBuf, int msgBufLen);
int gmdCreateD   (gmdHandle_t *pgmd, const char *dirName, char *msgBuf, int msgBufLen);
int gmdCreateDD  (gmdHandle_t *pgmd, const char *dirName, char *msgBuf, int msgBufLen);
int gmdCreateL   (gmdHandle_t *pgmd, const char *libName, char *msgBuf, int msgBufLen);
int gmdFree      (gmdHandle_t *pgmd);

int gmdLibraryLoaded(void);
int gmdLibraryUnload(void);

int  gmdGetScreenIndicator   (void);
void gmdSetScreenIndicator   (int scrind);
int  gmdGetExceptionIndicator(void);
void gmdSetExceptionIndicator(int excind);
int  gmdGetExitIndicator     (void);
void gmdSetExitIndicator     (int extind);
gmdErrorCallback_t gmdGetErrorCallback(void);
void gmdSetErrorCallback(gmdErrorCallback_t func);
int  gmdGetAPIErrorCount     (void);
void gmdSetAPIErrorCount     (int ecnt);

void gmdErrorHandling(const char *msg);
void gmdInitMutexes(void);
void gmdFiniMutexes(void);


#if defined(GMD_MAIN)    /* we must define some things only once */
# define GMD_FUNCPTR(NAME)  NAME##_t NAME = NULL
#else
# define GMD_FUNCPTR(NAME)  extern NAME##_t NAME
#endif


/* Prototypes for Dummy Functions */
int  GMD_CALLCONV d_gmdInitFromGDX (gmdHandle_t pgmd, const char *fileName);
int  GMD_CALLCONV d_gmdInitFromDict (gmdHandle_t pgmd, void *gmoPtr);
int  GMD_CALLCONV d_gmdInitFromDB (gmdHandle_t pgmd, void *gmdSrcPtr);
int  GMD_CALLCONV d_gmdRegisterGMO (gmdHandle_t pgmd, void *gmoPtr);
int  GMD_CALLCONV d_gmdCloseGDX (gmdHandle_t pgmd, int loadRemain);
int  GMD_CALLCONV d_gmdAddSymbolX (gmdHandle_t pgmd, const char *symName, int aDim, int stype, int userInfo, const char *explText, void **vDomPtrIn, const char *keyStr[], void **symPtr);
void * GMD_CALLCONV d_gmdAddSymbolXPy (gmdHandle_t pgmd, const char *symName, int aDim, int stype, int userInfo, const char *explText, void **vDomPtrIn, const char *keyStr[], int *status);
int  GMD_CALLCONV d_gmdAddSymbol (gmdHandle_t pgmd, const char *symName, int aDim, int stype, int userInfo, const char *explText, void **symPtr);
void * GMD_CALLCONV d_gmdAddSymbolPy (gmdHandle_t pgmd, const char *symName, int aDim, int stype, int userInfo, const char *explText, int *status);
int  GMD_CALLCONV d_gmdFindSymbol (gmdHandle_t pgmd, const char *symName, void **symPtr);
void * GMD_CALLCONV d_gmdFindSymbolPy (gmdHandle_t pgmd, const char *symName, int *status);
int  GMD_CALLCONV d_gmdGetSymbolByIndex (gmdHandle_t pgmd, int idx, void **symPtr);
void * GMD_CALLCONV d_gmdGetSymbolByIndexPy (gmdHandle_t pgmd, int idx, int *status);
int  GMD_CALLCONV d_gmdClearSymbol (gmdHandle_t pgmd, void *symPtr);
int  GMD_CALLCONV d_gmdCopySymbol (gmdHandle_t pgmd, void *tarSymPtr, void *srcSymPtr);
int  GMD_CALLCONV d_gmdFindRecord (gmdHandle_t pgmd, void *symPtr, const char *keyStr[], void **symIterPtr);
void * GMD_CALLCONV d_gmdFindRecordPy (gmdHandle_t pgmd, void *symPtr, const char *keyStr[], int *status);
int  GMD_CALLCONV d_gmdFindFirstRecord (gmdHandle_t pgmd, void *symPtr, void **symIterPtr);
void * GMD_CALLCONV d_gmdFindFirstRecordPy (gmdHandle_t pgmd, void *symPtr, int *status);
int  GMD_CALLCONV d_gmdFindFirstRecordSlice (gmdHandle_t pgmd, void *symPtr, const char *keyStr[], void **symIterPtr);
void * GMD_CALLCONV d_gmdFindFirstRecordSlicePy (gmdHandle_t pgmd, void *symPtr, const char *keyStr[], int *status);
int  GMD_CALLCONV d_gmdFindLastRecord (gmdHandle_t pgmd, void *symPtr, void **symIterPtr);
void * GMD_CALLCONV d_gmdFindLastRecordPy (gmdHandle_t pgmd, void *symPtr, int *status);
int  GMD_CALLCONV d_gmdFindLastRecordSlice (gmdHandle_t pgmd, void *symPtr, const char *keyStr[], void **symIterPtr);
void * GMD_CALLCONV d_gmdFindLastRecordSlicePy (gmdHandle_t pgmd, void *symPtr, const char *keyStr[], int *status);
int  GMD_CALLCONV d_gmdRecordMoveNext (gmdHandle_t pgmd, void *symIterPtr);
int  GMD_CALLCONV d_gmdRecordHasNext (gmdHandle_t pgmd, void *symIterPtr);
int  GMD_CALLCONV d_gmdRecordMovePrev (gmdHandle_t pgmd, void *symIterPtr);
int  GMD_CALLCONV d_gmdSameRecord (gmdHandle_t pgmd, void *symIterPtrSrc, void *symIterPtrtar);
int  GMD_CALLCONV d_gmdRecordHasPrev (gmdHandle_t pgmd, void *symIterPtr);
int  GMD_CALLCONV d_gmdGetElemText (gmdHandle_t pgmd, void *symIterPtr, char *txt);
int  GMD_CALLCONV d_gmdGetLevel (gmdHandle_t pgmd, void *symIterPtr, double *value);
int  GMD_CALLCONV d_gmdGetLower (gmdHandle_t pgmd, void *symIterPtr, double *value);
int  GMD_CALLCONV d_gmdGetUpper (gmdHandle_t pgmd, void *symIterPtr, double *value);
int  GMD_CALLCONV d_gmdGetMarginal (gmdHandle_t pgmd, void *symIterPtr, double *value);
int  GMD_CALLCONV d_gmdGetScale (gmdHandle_t pgmd, void *symIterPtr, double *value);
int  GMD_CALLCONV d_gmdSetElemText (gmdHandle_t pgmd, void *symIterPtr, const char *txt);
int  GMD_CALLCONV d_gmdSetLevel (gmdHandle_t pgmd, void *symIterPtr, double value);
int  GMD_CALLCONV d_gmdSetLower (gmdHandle_t pgmd, void *symIterPtr, double value);
int  GMD_CALLCONV d_gmdSetUpper (gmdHandle_t pgmd, void *symIterPtr, double value);
int  GMD_CALLCONV d_gmdSetMarginal (gmdHandle_t pgmd, void *symIterPtr, double value);
int  GMD_CALLCONV d_gmdSetScale (gmdHandle_t pgmd, void *symIterPtr, double value);
int  GMD_CALLCONV d_gmdSetUserInfo (gmdHandle_t pgmd, void *symPtr, int value);
int  GMD_CALLCONV d_gmdAddRecord (gmdHandle_t pgmd, void *symPtr, const char *keyStr[], void **symIterPtr);
void * GMD_CALLCONV d_gmdAddRecordPy (gmdHandle_t pgmd, void *symPtr, const char *keyStr[], int *status);
int  GMD_CALLCONV d_gmdDeleteRecord (gmdHandle_t pgmd, void *symIterPtr);
int  GMD_CALLCONV d_gmdGetKeys (gmdHandle_t pgmd, void *symIterPtr, int aDim, char *keyStr[]);
int  GMD_CALLCONV d_gmdGetKey (gmdHandle_t pgmd, void *symIterPtr, int idx, char *keyStr);
int  GMD_CALLCONV d_gmdGetDomain (gmdHandle_t pgmd, void *symPtr, int aDim, void **vDomPtrOut, char *keyStr[]);
int  GMD_CALLCONV d_gmdCopySymbolIterator (gmdHandle_t pgmd, void *symIterPtrSrc, void **symIterPtrtar);
void * GMD_CALLCONV d_gmdCopySymbolIteratorPy (gmdHandle_t pgmd, void *symIterPtrSrc, int *status);
int  GMD_CALLCONV d_gmdFreeSymbolIterator (gmdHandle_t pgmd, void *symIterPtr);
int  GMD_CALLCONV d_gmdMergeUel (gmdHandle_t pgmd, const char *uel, int *uelNr);
int  GMD_CALLCONV d_gmdInfo (gmdHandle_t pgmd, int infoKey, int *ival, double *dval, char *sval);
int  GMD_CALLCONV d_gmdSymbolInfo (gmdHandle_t pgmd, void *symPtr, int infoKey, int *ival, double *dval, char *sval);
int  GMD_CALLCONV d_gmdSymbolDim (gmdHandle_t pgmd, void *symPtr, int *aDim);
int  GMD_CALLCONV d_gmdSymbolType (gmdHandle_t pgmd, void *symPtr, int *stype);
int  GMD_CALLCONV d_gmdWriteGDX (gmdHandle_t pgmd, const char *fileName, int noDomChk);
int  GMD_CALLCONV d_gmdSetSpecialValues (gmdHandle_t pgmd, const double specVal[]);
int  GMD_CALLCONV d_gmdSetDebug (gmdHandle_t pgmd, int debugLevel);
int  GMD_CALLCONV d_gmdGetLastError (gmdHandle_t pgmd, char *msg);
int  GMD_CALLCONV d_gmdCheckDBDV (gmdHandle_t pgmd, int *dv);
int  GMD_CALLCONV d_gmdCheckSymbolDV (gmdHandle_t pgmd, void *symPtr, int *dv);
int  GMD_CALLCONV d_gmdGetFirstDBDV (gmdHandle_t pgmd, void **dvHandle);
void * GMD_CALLCONV d_gmdGetFirstDBDVPy (gmdHandle_t pgmd, int *status);
int  GMD_CALLCONV d_gmdGetFirstDVInSymbol (gmdHandle_t pgmd, void *symPtr, void **dvHandle);
void * GMD_CALLCONV d_gmdGetFirstDVInSymbolPy (gmdHandle_t pgmd, void *symPtr, int *status);
int  GMD_CALLCONV d_gmdDomainCheckDone (gmdHandle_t pgmd);
int  GMD_CALLCONV d_gmdGetFirstDVInNextSymbol (gmdHandle_t pgmd, void *dvHandle, int *nextavail);
int  GMD_CALLCONV d_gmdMoveNextDVInSymbol (gmdHandle_t pgmd, void *dvHandle, int *nextavail);
int  GMD_CALLCONV d_gmdFreeDVHandle (gmdHandle_t pgmd, void *dvHandle);
int  GMD_CALLCONV d_gmdGetDVSymbol (gmdHandle_t pgmd, void *dvHandle, void **symPtr);
void * GMD_CALLCONV d_gmdGetDVSymbolPy (gmdHandle_t pgmd, void *dvHandle, int *status);
int  GMD_CALLCONV d_gmdGetDVSymbolRecord (gmdHandle_t pgmd, void *dvHandle, void **symIterPtr);
void * GMD_CALLCONV d_gmdGetDVSymbolRecordPy (gmdHandle_t pgmd, void *dvHandle, int *status);
int  GMD_CALLCONV d_gmdGetDVIndicator (gmdHandle_t pgmd, void *dvHandle, int viol[]);
int  GMD_CALLCONV d_gmdInitUpdate (gmdHandle_t pgmd, void *gmoPtr);
int  GMD_CALLCONV d_gmdUpdateModelSymbol (gmdHandle_t pgmd, void *gamsSymPtr, int actionType, void *dataSymPtr, int updateType, int *noMatchCnt);
int  GMD_CALLCONV d_gmdCallSolver (gmdHandle_t pgmd, const char *solvername);
int  GMD_CALLCONV d_gmdCallSolverTimed (gmdHandle_t pgmd, const char *solvername, double *time);
int  GMD_CALLCONV d_gmdDenseSymbolToDenseArray (gmdHandle_t pgmd, void *cube, int vDim[], void *symPtr, int field);
int  GMD_CALLCONV d_gmdSparseSymbolToDenseArray (gmdHandle_t pgmd, void *cube, int vDim[], void *symPtr, void **vDomPtr, int field, int *nDropped);
int  GMD_CALLCONV d_gmdSparseSymbolToSqzdArray (gmdHandle_t pgmd, void *cube, int vDim[], void *symPtr, void **vDomSqueezePtr, void **vDomPtr, int field, int *nDropped);
int  GMD_CALLCONV d_gmdDenseArrayToSymbol (gmdHandle_t pgmd, void *symPtr, void **vDomPtr, void *cube, int vDim[]);
int  GMD_CALLCONV d_gmdDenseArraySlicesToSymbol (gmdHandle_t pgmd, void *symPtr, void **vDomSlicePtr, void **vDomPtr, void *cube, int vDim[]);

typedef int  (GMD_CALLCONV *gmdInitFromGDX_t) (gmdHandle_t pgmd, const char *fileName);
GMD_FUNCPTR(gmdInitFromGDX);
typedef int  (GMD_CALLCONV *gmdInitFromDict_t) (gmdHandle_t pgmd, void *gmoPtr);
GMD_FUNCPTR(gmdInitFromDict);
typedef int  (GMD_CALLCONV *gmdInitFromDB_t) (gmdHandle_t pgmd, void *gmdSrcPtr);
GMD_FUNCPTR(gmdInitFromDB);
typedef int  (GMD_CALLCONV *gmdRegisterGMO_t) (gmdHandle_t pgmd, void *gmoPtr);
GMD_FUNCPTR(gmdRegisterGMO);
typedef int  (GMD_CALLCONV *gmdCloseGDX_t) (gmdHandle_t pgmd, int loadRemain);
GMD_FUNCPTR(gmdCloseGDX);
typedef int  (GMD_CALLCONV *gmdAddSymbolX_t) (gmdHandle_t pgmd, const char *symName, int aDim, int stype, int userInfo, const char *explText, void **vDomPtrIn, const char *keyStr[], void **symPtr);
GMD_FUNCPTR(gmdAddSymbolX);
typedef void * (GMD_CALLCONV *gmdAddSymbolXPy_t) (gmdHandle_t pgmd, const char *symName, int aDim, int stype, int userInfo, const char *explText, void **vDomPtrIn, const char *keyStr[], int *status);
GMD_FUNCPTR(gmdAddSymbolXPy);
typedef int  (GMD_CALLCONV *gmdAddSymbol_t) (gmdHandle_t pgmd, const char *symName, int aDim, int stype, int userInfo, const char *explText, void **symPtr);
GMD_FUNCPTR(gmdAddSymbol);
typedef void * (GMD_CALLCONV *gmdAddSymbolPy_t) (gmdHandle_t pgmd, const char *symName, int aDim, int stype, int userInfo, const char *explText, int *status);
GMD_FUNCPTR(gmdAddSymbolPy);
typedef int  (GMD_CALLCONV *gmdFindSymbol_t) (gmdHandle_t pgmd, const char *symName, void **symPtr);
GMD_FUNCPTR(gmdFindSymbol);
typedef void * (GMD_CALLCONV *gmdFindSymbolPy_t) (gmdHandle_t pgmd, const char *symName, int *status);
GMD_FUNCPTR(gmdFindSymbolPy);
typedef int  (GMD_CALLCONV *gmdGetSymbolByIndex_t) (gmdHandle_t pgmd, int idx, void **symPtr);
GMD_FUNCPTR(gmdGetSymbolByIndex);
typedef void * (GMD_CALLCONV *gmdGetSymbolByIndexPy_t) (gmdHandle_t pgmd, int idx, int *status);
GMD_FUNCPTR(gmdGetSymbolByIndexPy);
typedef int  (GMD_CALLCONV *gmdClearSymbol_t) (gmdHandle_t pgmd, void *symPtr);
GMD_FUNCPTR(gmdClearSymbol);
typedef int  (GMD_CALLCONV *gmdCopySymbol_t) (gmdHandle_t pgmd, void *tarSymPtr, void *srcSymPtr);
GMD_FUNCPTR(gmdCopySymbol);
typedef int  (GMD_CALLCONV *gmdFindRecord_t) (gmdHandle_t pgmd, void *symPtr, const char *keyStr[], void **symIterPtr);
GMD_FUNCPTR(gmdFindRecord);
typedef void * (GMD_CALLCONV *gmdFindRecordPy_t) (gmdHandle_t pgmd, void *symPtr, const char *keyStr[], int *status);
GMD_FUNCPTR(gmdFindRecordPy);
typedef int  (GMD_CALLCONV *gmdFindFirstRecord_t) (gmdHandle_t pgmd, void *symPtr, void **symIterPtr);
GMD_FUNCPTR(gmdFindFirstRecord);
typedef void * (GMD_CALLCONV *gmdFindFirstRecordPy_t) (gmdHandle_t pgmd, void *symPtr, int *status);
GMD_FUNCPTR(gmdFindFirstRecordPy);
typedef int  (GMD_CALLCONV *gmdFindFirstRecordSlice_t) (gmdHandle_t pgmd, void *symPtr, const char *keyStr[], void **symIterPtr);
GMD_FUNCPTR(gmdFindFirstRecordSlice);
typedef void * (GMD_CALLCONV *gmdFindFirstRecordSlicePy_t) (gmdHandle_t pgmd, void *symPtr, const char *keyStr[], int *status);
GMD_FUNCPTR(gmdFindFirstRecordSlicePy);
typedef int  (GMD_CALLCONV *gmdFindLastRecord_t) (gmdHandle_t pgmd, void *symPtr, void **symIterPtr);
GMD_FUNCPTR(gmdFindLastRecord);
typedef void * (GMD_CALLCONV *gmdFindLastRecordPy_t) (gmdHandle_t pgmd, void *symPtr, int *status);
GMD_FUNCPTR(gmdFindLastRecordPy);
typedef int  (GMD_CALLCONV *gmdFindLastRecordSlice_t) (gmdHandle_t pgmd, void *symPtr, const char *keyStr[], void **symIterPtr);
GMD_FUNCPTR(gmdFindLastRecordSlice);
typedef void * (GMD_CALLCONV *gmdFindLastRecordSlicePy_t) (gmdHandle_t pgmd, void *symPtr, const char *keyStr[], int *status);
GMD_FUNCPTR(gmdFindLastRecordSlicePy);
typedef int  (GMD_CALLCONV *gmdRecordMoveNext_t) (gmdHandle_t pgmd, void *symIterPtr);
GMD_FUNCPTR(gmdRecordMoveNext);
typedef int  (GMD_CALLCONV *gmdRecordHasNext_t) (gmdHandle_t pgmd, void *symIterPtr);
GMD_FUNCPTR(gmdRecordHasNext);
typedef int  (GMD_CALLCONV *gmdRecordMovePrev_t) (gmdHandle_t pgmd, void *symIterPtr);
GMD_FUNCPTR(gmdRecordMovePrev);
typedef int  (GMD_CALLCONV *gmdSameRecord_t) (gmdHandle_t pgmd, void *symIterPtrSrc, void *symIterPtrtar);
GMD_FUNCPTR(gmdSameRecord);
typedef int  (GMD_CALLCONV *gmdRecordHasPrev_t) (gmdHandle_t pgmd, void *symIterPtr);
GMD_FUNCPTR(gmdRecordHasPrev);
typedef int  (GMD_CALLCONV *gmdGetElemText_t) (gmdHandle_t pgmd, void *symIterPtr, char *txt);
GMD_FUNCPTR(gmdGetElemText);
typedef int  (GMD_CALLCONV *gmdGetLevel_t) (gmdHandle_t pgmd, void *symIterPtr, double *value);
GMD_FUNCPTR(gmdGetLevel);
typedef int  (GMD_CALLCONV *gmdGetLower_t) (gmdHandle_t pgmd, void *symIterPtr, double *value);
GMD_FUNCPTR(gmdGetLower);
typedef int  (GMD_CALLCONV *gmdGetUpper_t) (gmdHandle_t pgmd, void *symIterPtr, double *value);
GMD_FUNCPTR(gmdGetUpper);
typedef int  (GMD_CALLCONV *gmdGetMarginal_t) (gmdHandle_t pgmd, void *symIterPtr, double *value);
GMD_FUNCPTR(gmdGetMarginal);
typedef int  (GMD_CALLCONV *gmdGetScale_t) (gmdHandle_t pgmd, void *symIterPtr, double *value);
GMD_FUNCPTR(gmdGetScale);
typedef int  (GMD_CALLCONV *gmdSetElemText_t) (gmdHandle_t pgmd, void *symIterPtr, const char *txt);
GMD_FUNCPTR(gmdSetElemText);
typedef int  (GMD_CALLCONV *gmdSetLevel_t) (gmdHandle_t pgmd, void *symIterPtr, double value);
GMD_FUNCPTR(gmdSetLevel);
typedef int  (GMD_CALLCONV *gmdSetLower_t) (gmdHandle_t pgmd, void *symIterPtr, double value);
GMD_FUNCPTR(gmdSetLower);
typedef int  (GMD_CALLCONV *gmdSetUpper_t) (gmdHandle_t pgmd, void *symIterPtr, double value);
GMD_FUNCPTR(gmdSetUpper);
typedef int  (GMD_CALLCONV *gmdSetMarginal_t) (gmdHandle_t pgmd, void *symIterPtr, double value);
GMD_FUNCPTR(gmdSetMarginal);
typedef int  (GMD_CALLCONV *gmdSetScale_t) (gmdHandle_t pgmd, void *symIterPtr, double value);
GMD_FUNCPTR(gmdSetScale);
typedef int  (GMD_CALLCONV *gmdSetUserInfo_t) (gmdHandle_t pgmd, void *symPtr, int value);
GMD_FUNCPTR(gmdSetUserInfo);
typedef int  (GMD_CALLCONV *gmdAddRecord_t) (gmdHandle_t pgmd, void *symPtr, const char *keyStr[], void **symIterPtr);
GMD_FUNCPTR(gmdAddRecord);
typedef void * (GMD_CALLCONV *gmdAddRecordPy_t) (gmdHandle_t pgmd, void *symPtr, const char *keyStr[], int *status);
GMD_FUNCPTR(gmdAddRecordPy);
typedef int  (GMD_CALLCONV *gmdDeleteRecord_t) (gmdHandle_t pgmd, void *symIterPtr);
GMD_FUNCPTR(gmdDeleteRecord);
typedef int  (GMD_CALLCONV *gmdGetKeys_t) (gmdHandle_t pgmd, void *symIterPtr, int aDim, char *keyStr[]);
GMD_FUNCPTR(gmdGetKeys);
typedef int  (GMD_CALLCONV *gmdGetKey_t) (gmdHandle_t pgmd, void *symIterPtr, int idx, char *keyStr);
GMD_FUNCPTR(gmdGetKey);
typedef int  (GMD_CALLCONV *gmdGetDomain_t) (gmdHandle_t pgmd, void *symPtr, int aDim, void **vDomPtrOut, char *keyStr[]);
GMD_FUNCPTR(gmdGetDomain);
typedef int  (GMD_CALLCONV *gmdCopySymbolIterator_t) (gmdHandle_t pgmd, void *symIterPtrSrc, void **symIterPtrtar);
GMD_FUNCPTR(gmdCopySymbolIterator);
typedef void * (GMD_CALLCONV *gmdCopySymbolIteratorPy_t) (gmdHandle_t pgmd, void *symIterPtrSrc, int *status);
GMD_FUNCPTR(gmdCopySymbolIteratorPy);
typedef int  (GMD_CALLCONV *gmdFreeSymbolIterator_t) (gmdHandle_t pgmd, void *symIterPtr);
GMD_FUNCPTR(gmdFreeSymbolIterator);
typedef int  (GMD_CALLCONV *gmdMergeUel_t) (gmdHandle_t pgmd, const char *uel, int *uelNr);
GMD_FUNCPTR(gmdMergeUel);
typedef int  (GMD_CALLCONV *gmdInfo_t) (gmdHandle_t pgmd, int infoKey, int *ival, double *dval, char *sval);
GMD_FUNCPTR(gmdInfo);
typedef int  (GMD_CALLCONV *gmdSymbolInfo_t) (gmdHandle_t pgmd, void *symPtr, int infoKey, int *ival, double *dval, char *sval);
GMD_FUNCPTR(gmdSymbolInfo);
typedef int  (GMD_CALLCONV *gmdSymbolDim_t) (gmdHandle_t pgmd, void *symPtr, int *aDim);
GMD_FUNCPTR(gmdSymbolDim);
typedef int  (GMD_CALLCONV *gmdSymbolType_t) (gmdHandle_t pgmd, void *symPtr, int *stype);
GMD_FUNCPTR(gmdSymbolType);
typedef int  (GMD_CALLCONV *gmdWriteGDX_t) (gmdHandle_t pgmd, const char *fileName, int noDomChk);
GMD_FUNCPTR(gmdWriteGDX);
typedef int  (GMD_CALLCONV *gmdSetSpecialValues_t) (gmdHandle_t pgmd, const double specVal[]);
GMD_FUNCPTR(gmdSetSpecialValues);
typedef int  (GMD_CALLCONV *gmdSetDebug_t) (gmdHandle_t pgmd, int debugLevel);
GMD_FUNCPTR(gmdSetDebug);
typedef int  (GMD_CALLCONV *gmdGetLastError_t) (gmdHandle_t pgmd, char *msg);
GMD_FUNCPTR(gmdGetLastError);
typedef int  (GMD_CALLCONV *gmdCheckDBDV_t) (gmdHandle_t pgmd, int *dv);
GMD_FUNCPTR(gmdCheckDBDV);
typedef int  (GMD_CALLCONV *gmdCheckSymbolDV_t) (gmdHandle_t pgmd, void *symPtr, int *dv);
GMD_FUNCPTR(gmdCheckSymbolDV);
typedef int  (GMD_CALLCONV *gmdGetFirstDBDV_t) (gmdHandle_t pgmd, void **dvHandle);
GMD_FUNCPTR(gmdGetFirstDBDV);
typedef void * (GMD_CALLCONV *gmdGetFirstDBDVPy_t) (gmdHandle_t pgmd, int *status);
GMD_FUNCPTR(gmdGetFirstDBDVPy);
typedef int  (GMD_CALLCONV *gmdGetFirstDVInSymbol_t) (gmdHandle_t pgmd, void *symPtr, void **dvHandle);
GMD_FUNCPTR(gmdGetFirstDVInSymbol);
typedef void * (GMD_CALLCONV *gmdGetFirstDVInSymbolPy_t) (gmdHandle_t pgmd, void *symPtr, int *status);
GMD_FUNCPTR(gmdGetFirstDVInSymbolPy);
typedef int  (GMD_CALLCONV *gmdDomainCheckDone_t) (gmdHandle_t pgmd);
GMD_FUNCPTR(gmdDomainCheckDone);
typedef int  (GMD_CALLCONV *gmdGetFirstDVInNextSymbol_t) (gmdHandle_t pgmd, void *dvHandle, int *nextavail);
GMD_FUNCPTR(gmdGetFirstDVInNextSymbol);
typedef int  (GMD_CALLCONV *gmdMoveNextDVInSymbol_t) (gmdHandle_t pgmd, void *dvHandle, int *nextavail);
GMD_FUNCPTR(gmdMoveNextDVInSymbol);
typedef int  (GMD_CALLCONV *gmdFreeDVHandle_t) (gmdHandle_t pgmd, void *dvHandle);
GMD_FUNCPTR(gmdFreeDVHandle);
typedef int  (GMD_CALLCONV *gmdGetDVSymbol_t) (gmdHandle_t pgmd, void *dvHandle, void **symPtr);
GMD_FUNCPTR(gmdGetDVSymbol);
typedef void * (GMD_CALLCONV *gmdGetDVSymbolPy_t) (gmdHandle_t pgmd, void *dvHandle, int *status);
GMD_FUNCPTR(gmdGetDVSymbolPy);
typedef int  (GMD_CALLCONV *gmdGetDVSymbolRecord_t) (gmdHandle_t pgmd, void *dvHandle, void **symIterPtr);
GMD_FUNCPTR(gmdGetDVSymbolRecord);
typedef void * (GMD_CALLCONV *gmdGetDVSymbolRecordPy_t) (gmdHandle_t pgmd, void *dvHandle, int *status);
GMD_FUNCPTR(gmdGetDVSymbolRecordPy);
typedef int  (GMD_CALLCONV *gmdGetDVIndicator_t) (gmdHandle_t pgmd, void *dvHandle, int viol[]);
GMD_FUNCPTR(gmdGetDVIndicator);
typedef int  (GMD_CALLCONV *gmdInitUpdate_t) (gmdHandle_t pgmd, void *gmoPtr);
GMD_FUNCPTR(gmdInitUpdate);
typedef int  (GMD_CALLCONV *gmdUpdateModelSymbol_t) (gmdHandle_t pgmd, void *gamsSymPtr, int actionType, void *dataSymPtr, int updateType, int *noMatchCnt);
GMD_FUNCPTR(gmdUpdateModelSymbol);
typedef int  (GMD_CALLCONV *gmdCallSolver_t) (gmdHandle_t pgmd, const char *solvername);
GMD_FUNCPTR(gmdCallSolver);
typedef int  (GMD_CALLCONV *gmdCallSolverTimed_t) (gmdHandle_t pgmd, const char *solvername, double *time);
GMD_FUNCPTR(gmdCallSolverTimed);
typedef int  (GMD_CALLCONV *gmdDenseSymbolToDenseArray_t) (gmdHandle_t pgmd, void *cube, int vDim[], void *symPtr, int field);
GMD_FUNCPTR(gmdDenseSymbolToDenseArray);
typedef int  (GMD_CALLCONV *gmdSparseSymbolToDenseArray_t) (gmdHandle_t pgmd, void *cube, int vDim[], void *symPtr, void **vDomPtr, int field, int *nDropped);
GMD_FUNCPTR(gmdSparseSymbolToDenseArray);
typedef int  (GMD_CALLCONV *gmdSparseSymbolToSqzdArray_t) (gmdHandle_t pgmd, void *cube, int vDim[], void *symPtr, void **vDomSqueezePtr, void **vDomPtr, int field, int *nDropped);
GMD_FUNCPTR(gmdSparseSymbolToSqzdArray);
typedef int  (GMD_CALLCONV *gmdDenseArrayToSymbol_t) (gmdHandle_t pgmd, void *symPtr, void **vDomPtr, void *cube, int vDim[]);
GMD_FUNCPTR(gmdDenseArrayToSymbol);
typedef int  (GMD_CALLCONV *gmdDenseArraySlicesToSymbol_t) (gmdHandle_t pgmd, void *symPtr, void **vDomSlicePtr, void **vDomPtr, void *cube, int vDim[]);
GMD_FUNCPTR(gmdDenseArraySlicesToSymbol);
#if defined(__cplusplus)
}
#endif
#endif /* #if ! defined(_GMDCC_H_) */
