

default:
	(cd Lib ; make ) 
programs:
	(cd Programs ; make ) 
test:
	(cd Test ; make ) 

clean:
	(cd Lib ; make clean )
	(cd Programs ; make clean )
	(cd Test ; make clean )

realclean:
	(cd Lib ; make realclean )
	(cd Programs ; make realclean )
	(cd Test ; make realclean )
