language: cpp
sudo: required
dist: xenial 

env:
  matrix:
    - MUMPS=1
    - MUMPS=0
addons:
  ssh_known_hosts: xgitlab.cels.anl.gov
  
before_install:
  - openssl aes-256-cbc -K $encrypted_key -iv $encrypted_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git clone git@xgitlab.cels.anl.gov:schanen/PIPSThirdPartyLibs.git
  - cp ./PIPSThirdPartyLibs/Cbc-2.9.8.tgz ./ThirdPartyLibs/CBC 
  - cp ./PIPSThirdPartyLibs/solvers.tar.gz ./ThirdPartyLibs/ASL
  - cp ./PIPSThirdPartyLibs/ma27-1.0.0.tar.gz ./ThirdPartyLibs/MA27
  - cp ./PIPSThirdPartyLibs/ma57-3.9.0.tar.gz ./ThirdPartyLibs/MA57
  - cp ./PIPSThirdPartyLibs/MUMPS_5.1.2.tar.gz ./ThirdPartyLibs/MUMPS
  - sudo apt-get update -qq
  - sudo apt-get install -y libblas-dev liblapack-dev 
  #- sudo apt-get install -y libmpich-dev mpich
  - sudo apt-get install -y libboost-all-dev
  - sudo apt-get install -y libblacs-openmpi1 libblacs-mpi-dev libscalapack-mpi-dev libscalapack-openmpi1
  
install:
  - cat /etc/lsb-release
  - ./build_3rdparty.sh 2
  - if [ $MUMPS -eq "1" ]; then cd ThirdPartyLibs/MUMPS; fi
  - if [ $MUMPS -eq "1" ]; then tar xvzf MUMPS_5.1.2.tar.gz; fi 
# sed the prefix path for MUMPS configure
  - if [ $MUMPS -eq "1" ]; then sed -i 's/$(HOME)\/git\/PIPS/HOME/g' Makefile_sample.inc; fi 
  - if [ $MUMPS -eq "1" ]; then sed -i "s|HOME|$PWD\/../..|g" Makefile_sample.inc; fi 
  - if [ $MUMPS -eq "1" ]; then cp Makefile_sample.inc MUMPS_5.1.2/Makefile.inc; fi 
  - if [ $MUMPS -eq "1" ]; then cd MUMPS_5.1.2; make -j; cd ..; fi 
  - if [ $MUMPS -eq "1" ]; then ln -sf ./MUMPS_5.1.2/include ./include; fi 
  - if [ $MUMPS -eq "1" ]; then ln -sf ./MUMPS_5.1.2/lib ./lib; cd ../..; fi 
  - ./build_pips.sh 2 
  
script:
  - cd build
  - cp ../PIPS-NLP/pipsnlp.parameter .
  - if [ $MUMPS -eq "0" ]; then env CTEST_OUTPUT_ON_FAILURE=1 make VERBOSE=1 test; fi 
  - if [ $MUMPS -eq "1" ]; then sed -i 's/BuildSchurComp 1/BuildSchurComp 3/g' pipsnlp.parameter; fi
  - if [ $MUMPS -eq "1" ]; then env CTEST_OUTPUT_ON_FAILURE=1 ctest -E linking --force-new-ctest-process; fi
